In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
## sentences for one hot encoding
sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy'
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]


In [4]:
## Define vocabulary size
vocab_size = 10000

In [6]:
## One Hot Representation
onehot_repr = [one_hot(words, vocab_size) for words in sentences]
print(onehot_repr)

[[6733, 7656, 3227, 7620], [6733, 7656, 3227, 8049], [6733, 8896, 3227, 4479], [719, 8072, 9163, 5110, 6670, 8072, 9163, 5110, 5164], [9926, 6733, 1830, 3227, 4303], [2790, 9785, 6678, 5110]]


In [8]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6733 7656 3227 7620]
 [   0    0    0    0 6733 7656 3227 8049]
 [   0    0    0    0 6733 8896 3227 4479]
 [8072 9163 5110 6670 8072 9163 5110 5164]
 [   0    0    0 9926 6733 1830 3227 4303]
 [   0    0    0    0 2790 9785 6678 5110]]


In [16]:
## Feature Representation
dim = 10
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')
print(model.summary())

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[[ 0.03574903,  0.0296347 , -0.00516541, -0.01061757,
         -0.02684062,  0.02877076,  0.00206392, -0.04958204,
         -0.01021159, -0.00672513],
        [ 0.03574903,  0.0296347 , -0.00516541, -0.01061757,
         -0.02684062,  0.02877076,  0.00206392, -0.04958204,
         -0.01021159, -0.00672513],
        [ 0.03574903,  0.0296347 , -0.00516541, -0.01061757,
         -0.02684062,  0.02877076,  0.00206392, -0.04958204,
         -0.01021159, -0.00672513],
        [ 0.03574903,  0.0296347 , -0.00516541, -0.01061757,
         -0.02684062,  0.02877076,  0.00206392, -0.04958204,
         -0.01021159, -0.00672513],
        [ 0.01841232,  0.0114697 , -0.0343297 , -0.01719364,
         -0.00883182, -0.02201923,  0.04658515, -0.00662309,
          0.01453373, -0.03536584],
        [ 0.0107365 , -0.01565458,  0.01877816, -0.04352342,
         -0.01300437,  0.04937836, -0.03847864, -0.00244296,
         -0.0205103 , -0.01629533],
        [-0.00669078, -0.04654776, -0.01114555,  0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 6733, 7656, 3227, 7620], dtype=int32)